services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bd_cocagne
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/bd_cocagne
    depends_on:
      - db
    ports:
      - "5001:5001"
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@iut-stdie.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - db
volumes:
  pgdata:
